# CodeRabbit Configuration
version: "0.1"

# Review Settings
reviews:
  profile: "chill" # Tone of the review (chill, assertive, etc.)
  request_changes_workflow: false # Don't automatically request changes
  high_level_summary: true # Provide a high-level summary
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "Draft"

# Chat Settings
chat:
  auto_reply: true # Allow CodeRabbit to reply to comments

# Linter Settings
linter:
  enabled: true
  level: "error" # Only report errors, not warnings
